application: lime-goatstone
version: 1
runtime: go
api_version: go1

handlers:

- url: /images
  static_dir: images

- url: /css
  static_dir: css
  mime_type: text/css

- url: /js
  static_dir: js
  mime_type: application/javascript

- url: /src
  static_dir: src
  mime_type: application/javascript

- url: /login
  static_files: login.html
  upload: login.html

#- url: /templates
#  script: _go_app
- url: /node_modules
  static_dir: node_modules
  mime_type: application/javascript

- url: /.*
  static_files:  index.html
  upload:  index.html
#  login: required
#  secure: always