application: salt-goatstone
version: 1
runtime: go
api_version: go1

handlers:

- url: /resource
  static_dir: resource

- url: /css
  static_dir: src/css
  mime_type: text/css

- url: /js
  static_dir: js
  mime_type: application/javascript

- url: /src/goatstone
  static_dir: src/goatstone
  mime_type: application/javascript

- url: /login
  static_files: login.html
  upload: login.html

- url: /node_modules
  static_dir: node_modules
  mime_type: application/javascript

- url: /.*
  static_files:  index.html
  upload:  index.html
